[build]
  command = "npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".env.local"]

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18" 